### ISSUE TITLE
java 客户端连接问题

### ISSUE THREAD

**Issue by longzhenwen** [baidu/sofa-pbrpc#118]
[](![image](https://cloud.githubusercontent.com/assets/5120383/18779222/9de861f4-81aa-11e6-9323-2ac53ff01c6a.png))

**Comment by longzhenwen** [comment]
[New I/O client worker #1-7] (com.jd.pbrpc.RpcClientConnection.exceptionCaught:58)  - Unexpected exception from downstream: 
java.lang.NullPointerException
        at com.jd.pbrpc.RpcChannelImpl.sendRequest(RpcChannelImpl.java:380)
        at com.jd.pbrpc.RpcChannelImpl.redispatchRequests(RpcChannelImpl.java:403)
        at com.jd.pbrpc.RpcChannelImpl.onNewSession(RpcChannelImpl.java:147)
        at com.jd.pbrpc.RpcClientHandler.onConnected(RpcClientHandler.java:28)
        at com.jd.pbrpc.RpcConnection.channelConnected(RpcConnection.java:69)
        at com.jd.pbrpc.RpcClientConnection.channelConnected(RpcClientConnection.java:20)
        at org.jboss.netty.channel.Channels.fireChannelConnected(Channels.java:233)
        at org.jboss.netty.channel.socket.nio.NioWorker$RegisterTask.run(NioWorker.java:784)
        at org.jboss.netty.channel.socket.nio.NioWorker.processRegisterTaskQueue(NioWorker.java:256)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:198)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
23 九月 2016 16:16:12,975 DEBUG [New I/O client worker #1-7] (com.jd.pbrpc.RpcClientConnection.channelClosed:50)  - channelClosed: o

**Comment by cyshi** [comment]
这套代码貌似不是我们维护的，你是在哪里找到的？
